### ISSUE TITLE
你好，数据能获取到，但是我拿不到中转后的数据。

### ISSUE THREAD

**Issue by julin171012** [fire4nt/wxlivespy#1]
`import time`
`import requests`

`url = 'http://localhost:8000/forward'`

`while True:`
`    try:`
`        response = requests.get(url)`
`        if response.status_code == 200:`
`            data = response.text`
`            # 处理数据，例如打印到控制台`
`            print(data)`
`        else:`
`            print("HTTP请求失败，状态码:", response.status_code)`
`    except requests.exceptions.RequestException as e:`
`        print("HTTP请求错误:", e)`
`    time.sleep(1)  # 1秒钟 `

代码如上。。。
错误信息：
HTTP请求错误: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /forward (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000294183D8760>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

查看本地端口
netstat -ano|findstr 8000

没有返回值。。  是中转没有启动吗？

**Comment by fire4nt** [comment]
转发地址是你的游戏进程监听的地址。
工具负责把弹幕数据通过http post请求转发到这个地址。

```mermaid
sequenceDiagram
    participant User as 用户
    participant Tool as 弹幕工具
    participant Browser as 浏览器
    participant Game as 游戏
    note over Game: 启动http服务<br>监听 http://ip:port/path
    User ->> Tool: 启动
    Tool ->> Browser: 启动
    User ->> Browser: 登录微信视频管理后台
    Browser ->> Tool: 房间弹幕数据
    User ->> Tool: 将Game监听地址 http://ip:port/path <br>作为转发地址填入弹幕工具
    Tool ->> Game: 将弹幕数据转发给Game
```

**Comment by julin171012** [comment]
不好意思，再次打扰到你。能给我一个简单的请求示例嘛。？

**Comment by fire4nt** [comment]
```python
from http.server import HTTPServer, BaseHTTPRequestHandler
import json

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    
    def do_POST(self):
        # Get the size of data
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length).decode('utf-8')
        
        # Try parsing the data as JSON. If it's not JSON, print as string.
        try:
            json_data = json.loads(post_data)
            print("Received POST request to:", self.path)
            print("JSON Body:")
            print(json.dumps(json_data, indent=4))
        except json.JSONDecodeError:
            print("Received POST request to:", self.path)
            print("Body (non-JSON):")
            print(post_data)

        # Respond to the client
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'OK')

if __name__ == "__main__":
    httpd = HTTPServer(('0.0.0.0', 8000), SimpleHTTPRequestHandler)
    print("Serving on port 8000...")
    httpd.serve_forever()
```

比如你用上面的python代码，监听 http://localhost:8000
然后你在弹幕工具里填`http://localhost:8000`，你就能看到转发的数据内容。

实际业务里，你需要填自己的游戏服务器（或客户端）的http地址。

**Comment by julin171012** [comment]
可以拿到数据了~~~非常感谢！！！！
