### ISSUE TITLE
我在使用代码获取不到http的转发数据

### ISSUE THREAD

**Issue by taintiankaixin** [fire4nt/wxlivespy#2]
![IMG_4576](https://github.com/fire4nt/wxlivespy/assets/151509390/248320e5-7305-4174-8dba-1e7dc7fdaffa)
采集不到转发信息

**Comment by fire4nt** [comment]
先确认一下 监听8000端口的python server有没有正确工作，你手动在命令行里向8000端口POST数据看看python代码能收到数据吗？
```
curl -X POST -d '{"data":"x"}' http://localhost:8000/xxx
```

**Comment by taintiankaixin** [comment]
![微信截图_20231214222923](https://github.com/fire4nt/wxlivespy/assets/151509390/88c26d02-9a7d-4da9-96c8-7d6c051ae2de)
python可以收到数据但是软件的数据发送不到8000端口

**Comment by Ikaros-521** [comment]
收不到+1
![image](https://github.com/fire4nt/wxlivespy/assets/40910637/8c10a584-13ee-4006-b030-db220af58a4e)

**Comment by Ikaros-521** [comment]
转发的话应该会有这个日志输出吧，实机使用时并没有
![image](https://github.com/fire4nt/wxlivespy/assets/40910637/1d852975-8c5d-48ae-9600-6e1a69b8e221)

**Comment by Ikaros-521** [comment]
> 转发的话应该会有这个日志输出吧，实机使用时并没有 ![image](https://private-user-images.githubusercontent.com/40910637/292193993-1d852975-8c5d-48ae-9600-6e1a69b8e221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTk0NzEsIm5iZiI6MTcwMzE1OTE3MSwicGF0aCI6Ii80MDkxMDYzNy8yOTIxOTM5OTMtMWQ4NTI5NzUtOGM1ZC00OGFlLTk2MDAtNmUxYTY5YjhlMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDExNDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZmZiZjU5YjIyYWQ5ZjZiZWVhOTYyNTIxNjI1ODhjYjI4YmYwMTkwYjcyNDllMGE2NGQ1ZmNkNGY2ZWYxODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vXKajCFN7RvBATcmWF4CGhA3B_GVIIPAef-ujfD5FWc)

![image](https://github.com/fire4nt/wxlivespy/assets/40910637/569c0f20-5ce8-43c3-b507-5dcd0be26d43)

**Comment by Ikaros-521** [comment]
呃呃呃，本地开了代理了。。。代理关了就好了
![image](https://github.com/fire4nt/wxlivespy/assets/40910637/76048da1-00aa-4db6-b617-ac4c7d7a2f9e)

**Comment by fire4nt** [comment]
我今天发现转发地址设置为`http://localhost:8000/forward`会出现如下报错：
```
[2024-02-02 16:07:06.172] [error] [main] forward error: Error: connect ECONNREFUSED ::1:8000
```
但是设置为 `http://127.0.0.1:8000/forward`就不会出错。

看起来应该是我测试用的python脚本只监听了ipv4的端口，但是 localhost 被解析为 ipv6的地址，就会失败。
如果大家遇到获取不到转发数据的情况，也可以考虑把 localhost 换成 127.0.0.1
