### ISSUE TITLE
打开chrome浏览器报错

### ISSUE THREAD

**Issue by daliang0222** [fire4nt/wxlivespy#3]
![image](https://github.com/fire4nt/wxlivespy/assets/19166994/819b2564-14dc-4ce0-818f-6beac3d67641)

你好，我这里提示打开Chrome浏览器出错，是要做什么配置吗，实际这个领下没有Chrome.exe文件

**Comment by fire4nt** [comment]
参考发布脚本
https://github.com/fire4nt/wxlivespy/blob/91887d54b1f9c00d35bc31983856e6f0811c212d/build.ps1#L16

你在自己的用户目录`C:\Users\XXX\`下，找一下形式是 `.cache\puppeteer\chrome\win64-117.0.5938.92\chrome-win64` 的目录，复制为代码仓库的 `assets/puppeteer_chrome/` 目录。

注意 `win64-117.0.5938.92` 这个是我电脑上的版本，npm install 实际安装的版本可能跟我不一样，你找到你安装好的版本就行。

**Comment by daliang0222** [comment]
感谢 ，按照你的方法 问题解决了
