### ISSUE TITLE
我想问下，electron 使用loadURL打开视频号助手后，扫码后无法进入首页，提示网络失败，或者说，直接重定向，这种知道怎么处理吗

### ISSUE THREAD

**Issue by Simba9980** [fire4nt/wxlivespy#5]
我想问下，electron 使用loadURL打开视频号助手后，扫码后无法进入首页，提示网络失败，或者说，直接重定向，这种知道怎么处理吗

**Comment by fire4nt** [comment]
我不是这方面的专家。我猜测是视频号后台的限制。比如通过 user agent 或者 一些其他的js代码方式检测到用户是从electron里访问的，就会拒绝请求。

这也是为什么代码里不直接使用electron打开视频号后台，而是使用puppeteer，毕竟puppeteer 用 Chromium，算是一个正常的浏览器，视频号服务器不太会直接拒绝正常的浏览器请求。
