### ISSUE TITLE
获取不到用户点赞行为

### ISSUE THREAD

**Issue by zhouyingxue427** [fire4nt/wxlivespy#6]
您好，目前监测页面上 只展示了总点赞数，但是当用户点赞的时候，在转发日志里面，没有某某用户点赞行为记录，既该工具所描述功能的第三项，也就是说代码decoded_type  是like这个场景监测不到
![image](https://github.com/fire4nt/wxlivespy/assets/144797635/9c7fad66-ec28-4767-8090-b8681c469ff4)

**Comment by zhouyingxue427** [comment]
还有几个问题：
1、可以监听到用户下播嘛
2、经过加密的用户的微信openid。同一个用户在同一个主播的不同直播场次会变化，如何与用户微信唯一的id相对应

或者有使用说明文档可以提供一下吗？

**Comment by fire4nt** [comment]
点赞行为应该是有的，等我周末确认一下。
另外关于用户的ID，也可以找到唯一的ID了。等我周末更新一下代码。

**Comment by zhouyingxue427** [comment]
> 点赞行为应该是有的，等我周末确认一下。 另外关于用户的ID，也可以找到唯一的ID了。等我周末更新一下代码。

用户下播行为，现在是监听不到的是嘛

**Comment by fire4nt** [comment]
> > 点赞行为应该是有的，等我周末确认一下。 另外关于用户的ID，也可以找到唯一的ID了。等我周末更新一下代码。
> 
> 用户下播行为，现在是监听不到的是嘛

等我周末看看吧，我记得网页数据的liveInfo里有个字段是标记直播状态的，程序可能没有解析和转发出来。

**Comment by zhouyingxue427** [comment]
好的，辛苦啦，不过您说的liveInfo应该是直播状态的，我想要的时候用户下线行为，刚才描述不清楚，就是与decoded_type=enter相对应的行为

**Comment by zhouyingxue427** [comment]
还有一个问题哈：页面上的转发地址，可以理解就是一个接口地址，你们把数据直接通过post发过去，我们这边接口直接接受你们给的数据，是这个意思嘛

**Comment by fire4nt** [comment]
> 还有一个问题哈：页面上的转发地址，可以理解就是一个接口地址，你们把数据直接通过post发过去，我们这边接口直接接受你们给的数据，是这个意思嘛

是的，可以参考 #1

**Comment by fire4nt** [comment]
> 您好，目前监测页面上 只展示了总点赞数，但是当用户点赞的时候，在转发日志里面，没有某某用户点赞行为记录，既该工具所描述功能的第三项，也就是说代码decoded_type 是like这个场景监测不到 ![image](https://private-user-images.githubusercontent.com/144797635/301415646-9c7fad66-ec28-4767-8090-b8681c469ff4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjM3MjYsIm5iZiI6MTcwNjg2MzQyNiwicGF0aCI6Ii8xNDQ3OTc2MzUvMzAxNDE1NjQ2LTljN2ZhZDY2LWVjMjgtNDc2Ny04MDkwLWI4NjgxYzQ2OWZmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwODQzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTVhZGE2N2YyYzZiMzYwMTQ0ODNiNTU0NWU0OGZkZTRjYjdmMTczMGU1ZTg4MjM4Nzc4ZmNmY2M4OTA2MTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JDDPpaA4yqmmIAv9EznViHXPZdsX6ewsT4JE39I7H40)

要测点赞行为，在长按直播间的点赞按钮一段时间再松开，就能看到点赞行为。
单独点一两下好像不会触发微信服务器推送。感觉这是直播平台的限制。

**Comment by fire4nt** [comment]
> 还有几个问题： 1、可以监听到用户下播嘛 2、经过加密的用户的微信openid。同一个用户在同一个主播的不同直播场次会变化，如何与用户微信唯一的id相对应
> 
> 或者有使用说明文档可以提供一下吗？

1. 监听不到用户立刻直播间的行为。
2. 更新到最新的代码，使用转发数据里的`decoded_openid`，这个值是同一用户在主播的不同直播场次中保持不变的ID。
