### ISSUE TITLE
开一个服务，可以同时监听多个账户嘛？

### ISSUE THREAD

**Issue by dylanzhou427** [fire4nt/wxlivespy#8]

**Comment by dylanzhou427** [comment]
可以打包成一个工具使用嘛

**Comment by dylanzhou427** [comment]
可以留个联系方式沟通一下嘛😂

**Comment by dylanzhou427** [comment]
还有一个问题，不知道是不是我操作不对，项目启动后，点击开始监听，网页登录后开始直播，是监听不到的，只能重新start才可以

**Comment by fire4nt** [comment]
> 可以打包成一个工具使用嘛

release页面有打包好的exe安装程序

https://github.com/fire4nt/wxlivespy/releases/tag/wxlive-spy%402024.0202.1638

**Comment by fire4nt** [comment]
> 还有一个问题，不知道是不是我操作不对，项目启动后，点击开始监听，网页登录后开始直播，是监听不到的，只能重新start才可以

是的，现在的实现没有做未开播的重试检测。所以需要：
1. 先开启直播
2. 打开wxlivespy工具
3. 点击wxlivespy工具的“开始监听”按钮

**Comment by fire4nt** [comment]
> 可以留个联系方式沟通一下嘛😂

可以发邮件 fire4nt.soft#gmail.com :)

**Comment by fire4nt** [comment]
> 开一个服务，可以同时监听多个账户嘛？

1. 技术原理上可行，本地开多个浏览器，登录多个不同的微信主播账户，就可以监听多个直播间的弹幕。但wxlivespy工具此前没考虑这种使用场景，尚不支持多开。
2. 实际使用可能有风险，同一个IP登录太多多个微信账户，微信可能会有风控吧。

**Comment by dylanzhou427** [comment]
<img width="905" alt="image" src="https://github.com/fire4nt/wxlivespy/assets/144797635/dbdcaa1a-34e6-4184-947a-de74be3d319e">

<img width="966" alt="image" src="https://github.com/fire4nt/wxlivespy/assets/144797635/c2eaef6f-a8b1-405b-9d23-ebad1ade39d9">
在请教一个问题
使用puppeteer.launch 定义一个无痕的的brower，使用newPage创建一个page的时候，为什么会新开一个窗口，且变成了正常的浏览器而不是无痕的
newPage我看puppeteer的API上应该新开一个标签页呀。

**Comment by dylanzhou427** [comment]
在Puppeteer中，browser.newPage()方法确实会创建一个新的浏览器页面（tab），但这个新页面是否为无痕模式取决于浏览器实例启动时的配置。如果整个浏览器是在无痕模式下启动的，那么通过newPage()打开的新页面也会继承这个模式，即它们同样处于无痕浏览状态。

然而，在你提供的代码片段中，虽然指定了启动Chrome浏览器时启用隐私浏览模式（无痕模式）的相关命令行参数，但是并没有明确说明browser实例确实是基于这些参数在无痕模式下启动的。如果在启动浏览器时没有正确应用无痕模式的配置选项，那么即使调用browser.newPage()创建新的页面，这些页面也不会自动进入无痕模式。

若要确保新页面始终在无痕模式下打开，需要保证在使用puppeteer.launch(options)时传递的options对象已经包含了正确的启动参数来开启隐私浏览模式。如前所述，示例中的args数组包含了'--incognito'，这意味着如果该配置被正确应用，则新创建的页面应处于无痕浏览模式下。

这看起来我的代码没啥问题啊，应该是在无痕浏览模式下新开一个tab页的。但是执行结果却是上面那种的
